CREATE OR REPLACE PROCEDURE Build_SIM_BOM."BMATHUB_BASE".P_ROOT_CORE_BUILD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO Build_SIM_BOM."BMATHUB_BASE".T_COMPRESS_BOM_CORE (
        INPUT_ITEM_ID,
	    ITEM_CLASS_NM,
	    OUTPUT_ITEM_ID,
	    LOC 
    ) 
    SELECT 
        ROOT.ITEM_ID,
        BOM.ITEM_CLASS_NM,
        BOM.OUTPUT_ITEM_ID,
        BOM.LOC
    FROM Build_SIM_BOM."BMATHUB_XFRM".V_ORIG_BOM AS BOM
    JOIN Build_SIM_BOM."BMATHUB_BASE".T_ITEM_DETAIL_ROOT AS ROOT
    ON BOM.INPUT_ITEM_ID = ROOT.ITEM_ID;   
RETURN 'Data Insert into table successfully';
END;
$$;
call Build_SIM_BOM."BMATHUB_BASE".P_MASTER_ROOT_MAINTAIN();  
