CREATE OR REPLACE PROCEDURE Build_SIM_BOM."BMATHUB_BASE".P_ROOT_CORE_BUILD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO Build_SIM_BOM."BMATHUB_BASE".T_COMPRESS_BOM_CORE (
        INPUT_ITEM_ID,
	    ITEM_CLASS_NM,
	    OUTPUT_ITEM_ID,
	    LOC 
    ) 
    SELECT 
        ROOT.ITEM_ID,
        BOM.ITEM_CLASS_NM,
        BOM.OUTPUT_ITEM_ID,
        BOM.LOC
    FROM Build_SIM_BOM."BMATHUB_BASE".T_ORIG_BOM AS BOM
    JOIN Build_SIM_BOM."BMATHUB_BASE".T_ITEM_DETAIL_ROOT AS ROOT
    ON BOM.INPUT_ITEM_ID = ROOT.ITEM_ID;

    UPDATE Build_SIM_BOM."BMATHUB_BASE".T_COMPRESS_BOM_CORE AS TARGET
    SET LOC = 
        CASE
            WHEN TARGET.ITEM_CLASS_NM = RULES.ITEM_CLASS_NM THEN RULES.LOCATION_ID
            ELSE NULL
        END
    FROM Build_SIM_BOM."BMATHUB_BASE".T_METADATA_RULES AS RULES
    WHERE TARGET.ITEM_CLASS_NM = RULES.ITEM_CLASS_NM;    
RETURN 'Data Insert into table successfully';
END;
$$;
call Build_SIM_BOM."BMATHUB_BASE".P_ROOT_CORE_BUILD();


