CREATE OR REPLACE VIEW Build_SIM_BOM."BMATHUB_XFRM".V_METADATA_RULES(
   ITEM_CLASS_NM,
   LOCATION_ID  
) AS SELECT 
   ITEM_CLASS_NM,
   LOCATION_ID 
FROM 
Build_SIM_BOM."BMATHUB_BASE".T_METADATA_RULES;