CREATE OR REPLACE VIEW Build_SIM_BOM."BMATHUB_XFRM".V_COMPRESS_BOM_CORE (
    INPUT_ITEM_ID,
	ITEM_CLASS_NM,
	OUTPUT_ITEM_ID,
    BOM_NUM,
	LOC 
) AS SELECT
        BOM.INPUT_ITEM_ID,
	    BOM.ITEM_CLASS_NM,
	    BOM.OUTPUT_ITEM_ID,
        BOM.BOM_NUM,
	    BOM.LOC
FROM 
Build_SIM_BOM."BMATHUB_BASE".T_COMPRESS_BOM_CORE AS BOM;