CREATE OR REPLACE VIEW Build_SIM_BOM."BMATHUB_XFRM".V_ITEM_DETAIL_ROOT(
  ITEM_ID,
  ITEM_CLASS_NM,
  ITEM_DSC,
  DELETE_IND
) AS SELECT
  ITEM_ID,
  ITEM_CLASS_NM,
  ITEM_DSC,
  DELETE_IND
FROM 
Build_SIM_BOM."BMATHUB_BASE".T_ITEM_DETAIL_ROOT;