CREATE OR REPLACE VIEW Build_SIM_BOM."BMATHUB_XFRM".V_ORIG_BOM (
    INPUT_ITEM_ID,
	ITEM_CLASS_NM,
	OUTPUT_ITEM_ID,
	LOC 
) AS SELECT
        INPUT_ITEM_ID,
	    ITEM_CLASS_NM,
	    OUTPUT_ITEM_ID,
	    LOC 
FROM 
Build_SIM_BOM."BMATHUB_BASE".T_ORIG_BOM;