CREATE OR REPLACE VIEW Build_SIM_BOM."BMATHUB_ANALYSIS".V_SIM_BOM(
  ITEM,
  ITEM_CLASS_NM,
  ANCHOR_ITEM_ID,
  BOM_NUM,
  LOC,
  CREATE_DATE,
  CREATE_USER,
  ITEM.ITEM_DSC     
)
AS SELECT
  BOM.ITEM,
  BOM.ITEM_CLASS_NM,
  BOM.ANCHOR_ITEM_ID,
  BOM.BOM_NUM,
  BOM.LOC,
  CURRENT_DATE AS CREATE_DATE,
  'SYSTEM' AS CREATE_USER,
  ITEM.ITEM_DSC  
FROM
  Build_SIM_BOM."BMATHUB_XFRM".V_COMPRESS_BOM_CORE AS BOM
JOIN
  Build_SIM_BOM."BMATHUB_XFRM".V_ITEM_DETAIL_ROOT AS ITEM
  ON BOM.ITEM = ITEM.ITEM_ID;

        