CREATE OR REPLACE STAGE Build_SIM_BOM."MASTER_DATA".STAGE_ITEM;
PUT file://C:/Users/yogeshwar.s/Desktop/ITEM.csv @Build_SIM_BOM."MASTER_DATA".STAGE_ITEM;
CREATE OR REPLACE FILE FORMAT FORMATE
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER = 1;
COPY INTO Build_SIM_BOM."MASTER_DATA".ITEM 
FROM @Build_SIM_BOM."MASTER_DATA".STAGE_ITEM/ITEM.csv
FILE_FORMAT = (FORMAT_NAME = 'FORMATE', TYPE = CSV);