CREATE OR REPLACE STAGE Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION;
PUT file://C:/Users/yogeshwar.s/Desktop/LOCATION.csv @Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION;

COPY INTO Build_SIM_BOM."MASTER_DATA".LOCATION 
FROM @Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION/LOCATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FORMATE', TYPE = CSV);
