CREATE OR REPLACE STAGE Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION;
PUT file://C:/Users/yogeshwar.s/Desktop/LOCATION.csv @Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION;

CREATE OR REPLACE FILE FORMAT FORMATE
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER = 1;

COPY INTO Build_SIM_BOM."MASTER_DATA".LOCATION 
FROM @Build_SIM_BOM."MASTER_DATA".STAGE_LOCATION/LOCATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FORMATE', TYPE = CSV);