CREATE OR REPLACE STAGE Build_SIM_BOM."MASTER_DATA".STAGE_ORIG_BOM;
PUT file://C:/Users/yogeshwar.s/Desktop/ORIG_BOM.csv @Build_SIM_BOM."MASTER_DATA".STAGE_ORIG_BOM;
COPY INTO Build_SIM_BOM."MASTER_DATA".ORIG_BOM 
FROM @Build_SIM_BOM."MASTER_DATA".STAGE_ORIG_BOM/ORIG_BOM.csv
FILE_FORMAT = (FORMAT_NAME = 'FORMATE', TYPE = CSV);